export * from "./Account"
export * from './AddCard';
export * from './Cards';
export * from "./GenericRegister"
export * from "./Home"
export * from "./Landing"
export * from "./Profile"
export * from "./TransactionAmount"
export * from "./TransferInto"
export * from "./TransferMoney"
